{
  imports = [
    ./nvim-window-picker
    ./telescope
    ./auto-pairs.nix
    ./blankline.nix
    ./bufferline.nix
    ./dressing.nix
    ./lazygit.nix
    ./mini-icons.nix
    ./neo-tree.nix
    ./noice.nix
    ./notify.nix
    ./nui.nix
    ./nvim-ufo.nix
    ./toggleterm.nix
    ./vim-surround.nix
    ./which-key.nix
  ];
}
